apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
    - name: apikey
      description: the ibmcloud api key
    - name: resourceGroup
      description: Region of the App Configuration instance
    - name: imageUrl
      description: url of the built image
    - name: clusterName
      description: The IBM Cloud Kubernetes cluster name
    - name: featureFilePath
      description: JSON file path where the App Configuration feature details are stored
  tasks:
    - name: appconfiguration-ci
      taskRef: 
        name: appconfiguration-ci
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
        - name: resourceGroup
          value: $(params.resourceGroup)
        - name: imageUrl
          value: $(params.imageUrl)
        - name: apikey
          value: $(params.apikey)
        - name: guid
          value: $(params.guid)
        - name: region
          value: $(params.region)
        - name: collection_id
          value: $(params.collection_id)
        - name: featureFilePath
          value: $(params.featureFilePath)
        - name: clusterName
          value: $(params.clusterName)
        - name: task-pvc
          value: $(params.pipeline-pvc)          