apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
    - name: apikey
      description: the ibmcloud api key
    - name: region
      description: Region of the App Configuration instance
    - name: guid
      description: Id of the App Configuration instance
    - name: collection_id
      description: name of the App Configuration collection
  resourcetemplates:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
        parameters: $(params.parameters)
        GIT_TOKEN: $(params.gitToken)
        REGION: ${params.region}
        GUID: ${params.guid}        
        COLLECTIONID: ${params.collection_id}        
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline
        resources:
          - name: app-image
            resourceRef:
              name: image-to-build          
        params:
          - name: pipeline-pvc
            value: pipelinerun-$(uid)-pvc
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: apikey
            value: $(params.apikey)
          - name: guid
            value: $(params.guid)
          - name: region
            value: $(params.region)    
          - name: collection_id
            value: $(params.collection_id)
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc                      
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding
spec:
  params:
    - name: branch
      value: $(params.branch)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener
spec:
  triggers:
    - binding:
        name: trigger-binding
      template:
        name: trigger-template